### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-JeroRoque#1]
[Fases-de-Gestión-de-Proyectos-Jeronima-Roque.pdf](https://github.com/user-attachments/files/16773963/Fases-de-Gestion-de-Proyectos-Jeronima-Roque.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..Calificacion 20
